#!/bin/bash
total 12                                                                                                                                                                  

drwxr-xr-x 2 root root 74 Nov 30 18:01 .                                                                                                                                  

drwxr-xr-x 4 root root 60 Nov 30 16:59 ..                                                                                                                                 

-rwxr--r-- 1 root root 16 Nov 30 17:29 0-current_working_directory                                                                                                        

-rwxr--r-- 1 root root 19 Nov 30 18:01 1-listit                                                                                                                           

-rw-r--r-- 1 root root 24 Nov 30 17:24 README.md