#!/bin/bash
-rwxr--r-- 1 root root 16 Nov 30 17:29 0-current_working_directory                                                                                                        

-rwxr--r-- 1 root root 87 Nov 30 18:46 1-listit                                                                                                                           

-rwxr--r-- 1 root root 21 Nov 30 18:49 2-bring_me_home                                                                                                                    

-rw-r--r-- 1 root root 24 Nov 30 17:24 README.md
